apiVersion: inference.opendatahub.io/v1alpha1
kind: ExternalModel
metadata:
  name: aws-gpt-oss-20b
  namespace: external-models
spec:
  modelName: openai.gpt-oss-20b
  externalProviderRefs:
    - ref:
        name: bedrock
      targetModel: openai.gpt-oss-20b
      apiFormat: openai-chat
      path: /v1/chat/completions
