apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: redhat-ods-monitoring
stringData:
  access_key_id: minio
  access_key_secret: minio123
  bucketnames: loki
  endpoint: http://minio.redhat-ods-monitoring.svc:9000
  region: us-east-1
type: Opaque
