apiVersion: maas.opendatahub.io/v1alpha1
kind: ExternalModel
metadata:
  name: azure-gpt-4-1-mini
  namespace: external-models
spec:
  provider: azure-openai
  targetModel: gpt-4-1-mini
  endpoint: maas-aoai-7c8wm-eb594.openai.azure.com
  credentialRef:
    name: azure-openai-api-key
