apiVersion: maas.opendatahub.io/v1alpha1
kind: ExternalModel
metadata:
  name: gemini-2-5-flash
  namespace: external-models
spec:
  provider: openai
  targetModel: gemini-2.5-flash
  endpoint: generativelanguage.googleapis.com
  credentialRef:
    name: gemini-api-key
